/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:43a3784e-3457-4bb5-b92d-7852d8b5c1a8",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_gae11yuZ8",
    "aws_user_pools_web_client_id": "686u8ulplkkbfo1ka7rlirrptg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ht3lkyqsjvay7m67fwesfrqy3a.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qw3mabseungsbmyexr5x3djnku"
};


export default awsmobile;
