/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://zbjn7xigkbaxfcufacu77idj7u.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qveau77k6rgo5bnuta7hspeybm",
    "aws_cognito_identity_pool_id": "eu-west-2:493c8975-5a8e-4203-a4b4-219fa7fd1b93",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_2DzclgFOG",
    "aws_user_pools_web_client_id": "7ubrfd4s9c99up6actpklddcf1",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    }
};


export default awsmobile;
